services:
  database-user:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 5032
    ports:
      - "5032:5432"
    volumes:
      - userdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=userdatabase
  testDb:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 1033
    ports:
      - "1033:5432"
    volumes:
      - coursedata:/var/lib/postgresql/testdata
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_data
  app-user:
    build: .
    restart: always
    network_mode: bridge
    container_name: user_service
    expose:
      - 5000
      - 5001
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - database-user
    links:
      - database-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-user:5432/userdatabase
volumes:
  userdata: